// No Copyright.

#pragma once

#include "NativeGameplayTags.h"

namespace AuraGameplayTags
{
	/** Input Tags */
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_1);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_2);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_3);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_4);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Shift);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_LMB);
	AURA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_RMB);
}
